config/routes.rb
Rails.application.routes.draw do
  resources :bookings, only: :index
  resources :flights do
    resources :bookings
  end
  resources :planes
  resources :seat_configurations do
    collection do
      get :available_rows
      get :available_seats
    end
  end
  resources :categories
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :dashboard, only: :index 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/plane.rb
# == Schema Information
#
# Table name: planes
#
#  id           :bigint           not null, primary key
#  name         :string
#  plane_number :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Plane < ApplicationRecord
  validates :name, presence: true
  validates :plane_number, presence: true, uniqueness: true

  has_one :flight, dependent: :destroy
  has_many :seat_configurations, dependent: :destroy

  accepts_nested_attributes_for :seat_configurations, allow_destroy: true

  scope :without_flight, -> do
    left_outer_joins(:flight).where(flights: { id: nil })
  end

  def full_name
    "#{name} / #{plane_number}"
  end
end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_plane, only: [:show, :edit, :update, :destroy]
  before_action :set_seat_category, only: [:new, :create, :edit, :update]

  # GET /planes
  # GET /planes.json
  def index
    @planes = Plane.all
  end

  # GET /planes/1
  # GET /planes/1.json
  def show
  end

  # GET /planes/new
  def new
    @plane = Plane.new
    @plane.seat_configurations.build
  end

  # GET /planes/1/edit
  def edit
  end

  # POST /planes
  # POST /planes.json
  def create
    @plane = Plane.new(plane_params)

    respond_to do |format|
      if @plane.save
        format.html { redirect_to @plane, notice: 'Plane was successfully created.' }
        format.json { render :show, status: :created, location: @plane }
      else
        format.html { render :new }
        format.json { render json: @plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planes/1
  # PATCH/PUT /planes/1.json
  def update
    respond_to do |format|
      if @plane.update(plane_params)
        format.html { redirect_to @plane, notice: 'Plane was successfully updated.' }
        format.json { render :show, status: :ok, location: @plane }
      else
        format.html { render :edit }
        format.json { render json: @plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planes/1
  # DELETE /planes/1.json
  def destroy
    @plane.destroy
    respond_to do |format|
      format.html { redirect_to planes_url, notice: 'Plane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plane
      @plane = Plane.find(params[:id])
    end

    def set_seat_category
      @seat_catgories = Category.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plane_params
      params.require(:plane).permit(:name, :plane_number,
        seat_configurations_attributes: [:category_id, :seats_in_row, :number_of_rows, :base_price, :_destroy]
      )
    end
end

app/helpers/planes_helper.rb
module PlanesHelper
end

app/views/planes/_form.html.erb
<%= form_with(model: plane, local: true) do |form| %>
  <% if plane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plane.errors.count, "error") %> prohibited this plane from being saved:</h2>

      <ul>
      <% plane.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :plane_number %>
    <%= form.text_field :plane_number %>
  </div>

  <% if plane.new_record? %>
    <% @seat_catgories.each do |category| %>
      <%= form.fields_for :seat_configurations do |seat_form| %>
        <h2><%= "Category: #{category.name}" %></h2>
        <hr>
        <%= seat_form.hidden_field :category_id, value: category.id %>
        
        <div class="field">
          <%= seat_form.label :seats_in_row %>
          <%= seat_form.number_field :seats_in_row %>
        </div>

        <div class="field">
          <%= seat_form.label :number_of_rows %>
          <%= seat_form.number_field :number_of_rows %>
        </div>

        <div class="field">
          <%= seat_form.label :base_price %>
          <%= seat_form.number_field :base_price %>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <%= form.fields_for :seat_configurations do |seat_form| %>
      <h2><%= "Category: #{seat_form.object.try(:category).try(:name)}" %></h2>
      <hr>
      <%= seat_form.hidden_field :category_id, value: seat_form.object.try(:category_id) %>
      
      <div class="field">
        <%= seat_form.label :seats_in_row %>
        <%= seat_form.number_field :seats_in_row %>
      </div>

      <div class="field">
        <%= seat_form.label :number_of_rows %>
        <%= seat_form.number_field :number_of_rows %>
      </div>

      <div class="field">
        <%= seat_form.label :base_price %>
        <%= seat_form.number_field :base_price %>
      </div>
    <% end %>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/planes/edit.html.erb
<h1>Editing Plane</h1>

<%= render 'form', plane: @plane %>

<%= link_to 'Show', @plane %> |
<%= link_to 'Back', planes_path %>

app/views/planes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Planes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Plane number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planes.each do |plane| %>
      <tr>
        <td><%= plane.name %></td>
        <td><%= plane.plane_number %></td>
        <td><%= link_to 'Show', plane %></td>
        <td><%= link_to 'Edit', edit_plane_path(plane) %></td>
        <td><%= link_to 'Destroy', plane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plane', new_plane_path %>

app/views/planes/new.html.erb
<h1>New Plane</h1>

<%= render 'form', plane: @plane %>

<%= link_to 'Back', planes_path %>

app/views/planes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plane.name %>
</p>

<p>
  <strong>Plane number:</strong>
  <%= @plane.plane_number %>
</p>

<%= link_to 'Edit', edit_plane_path(@plane) %> |
<%= link_to 'Back', planes_path %>