config/routes.rb
Rails.application.routes.draw do
  resources :bookings, only: :index
  resources :flights do
    resources :bookings
  end
  resources :planes
  resources :seat_configurations do
    collection do
      get :available_rows
      get :available_seats
    end
  end
  resources :categories
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :dashboard, only: :index 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <% if user_signed_in? %>
    <div class="container">
      <%= link_to "Flight Booking", authenticated_root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", authenticated_root_path %></li>
          <% if current_user.admin? %>
            <li><%= link_to "Seat Category", categories_path %></li>
            <li><%= link_to "Plane", planes_path %></li>
            <li><%= link_to "Flight", flights_path %></li>
          <% else %>
          <% end %>
          <li><%= link_to "Booking", bookings_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete, data: { no_turbolink: true } %></li>
        </ul>
      </nav>
    </div>
  <% else %>
    <div class="container">
      <%= link_to "Flight Booking", unauthenticated_root_path, id: "logo" %>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flight Booking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>